### PR TITLE
Update to Swift 5/Xcode 10

### PR DESCRIPTION
**Pull request by weakfl**
- convert to Swift 5
- update project to recommended settings
- update podspec
- update .swift-version
- update README
- bump version

```
$ pod lib lint

 -> LocationPicker (1.4.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description

LocationPicker passed validation.
```

### CODE REVIEW

**Review by cburnham4 — APPROVED** [review]

**Comment by weakfl** [comment]
@almassapargali would be nice if you could merge this...

**Comment by almassapargali** [comment]
Hey @weakfl, sorry for delays, I really don't have time for maintaining LocationPicker these days. If you're interested in taking on as collaborator on GitHub and Cocoapods please write me at my username at gmail dot com.

**Comment by weakfl** [comment]
@almassapargali Sure, thanks. You should've received an email...

**Comment by almassapargali** [comment]
@weakfl gave you a push access. What's your CocoaPods trunk email, so you can release new versions?

**Comment by weakfl** [comment]
Thanks @almassapargali 

> What's your CocoaPods trunk email

It's the same as my github email, just had to register...

**Comment by almassapargali** [comment]
Hey @weakfl, I've added you as an owner on CocoaPods, now you can release new versions by yourself. Thank you very much for your willing to help!

**Review by almassapargali — APPROVED** [review]
lgtm

**Pull request merged**
