### PR TITLE
iOS 13 searchbar ui issue when present

### PR DESCRIPTION
**Pull request by mohsinalimat**
iOS 13 searchbar ui issue when present LocationPickerViewController

### CODE REVIEW

**Comment by weakfl** [comment]
@mohsinalimat Is this still an issue? I can't reproduce it with Xcode 11 GM.

**Comment by mohsinalimat** [comment]
I didn’t check it, i will check it and get back to you

[Mohsinali Matiya - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=5oxxb)	[5oxxb]

On September 12, 2019 at 8:18 GMT, weakfl <notifications@github.com> wrote:

[@mohsinalimat](https://github.com/mohsinalimat) Is this still an issue? I can't reproduce it with Xcode 11 GM.

**Comment by LoopingLouieX** [comment]
Well, I think this is still an issue.
After downloading the current branch the demo app is showing the following, even after adding the additional line of code in LocationPickerViewController:

Screenshot 2019-10-12 at 10 56 15

**Comment by weakfl** [comment]
Should be fixed in `1.4.1`, please re-open if this is still an issue.

**Pull request closed without merging**
