### PR TITLE
Adding podspec file and updaing README

### PR DESCRIPTION
**Pull request by bharatkrishna**
I added a podspec file so that people who use cocoapods would be able to easily install this library.

### CODE REVIEW

**Comment by almassapargali** [comment]
Please remove changes from LocationPickerViewController.swift, I'm on vacation now, will merge Sunday.

**Comment by bharatkrishna** [comment]
I have reverted my change to LocationPickerViewController.swift. I have a separate issue open for it which you could address when you are back.

**Comment by bharatkrishna** [comment]
After you merger the changes for adding cocoa pod, you might have to do a 

> pod spec lint LocationPicker.podspec 

and push it to trunk by doing

> pod trunk push LocationPicker.podspec

I was not able to add these to cocoapods trunk since I didn't have authorization to this repo. In case you'd want to refer to docs about this(could go straight to Step 2: Validation):
- http://code.tutsplus.com/tutorials/creating-your-first-cocoapod--cms-24332
- https://guides.cocoapods.org/making/using-pod-lib-create

Thanks for making this great and useful library.

**Comment by almassapargali** [comment]
Thanks, merged 👍

**Pull request merged**
